const slider = tns({
  container: '#slider',
  mode: "gallery",
  slideBy: 'page',
  animateIn: "fadeIn",
  animateOut: "fadeOut",
  loop: true,
  nav: false,
  autoplay: true,
  swipeAngle: false,
  viewportMax: true,
  autoplayButtonOutput: false,
  lazyload: true,
  controls: false,
  autoplayTimeout: 10000,
  items: 1,
  speed: 2000,
  animateDelay: 10000,
});
